### ISSUE TITLE
stress-ng returns running mandoc failed: signal: killed, stderr: 

### ISSUE THREAD

**Issue by foursixnine** [thkukuk/rpm2docserv#12]
When trying to query stress-ng,

https://manpages.opensuse.org/Tumbleweed/stress-ng/stress-ng.1.en.html

Error message: convert("/srv/rpm2docserv/Tumbleweed/stress-ng/stress-ng.1.en.gz"): running mandoc failed: signal: killed, stderr:

**Comment by thkukuk** [comment]
That's a mandoc problem, nothing I can fix.
I created https://bugzilla.suse.com/show_bug.cgi?id=1209830 for this.
