### ISSUE TITLE
Loading chameleon.css from net breaks layout

### ISSUE THREAD

**Issue by thkukuk** [thkukuk/rpm2docserv#2]
@hellcp 
I did implement an "IsOffline" variable for the templates to decide, if we can access the full network or should only use local files at build time.

If I enable the "mega menu" button, it works if I don't use  `<style src="https://static.opensuse.org/chameleon-3.0/dist/css/chameleon.css"></style>` but still inline the chameleon style. Any ideas?

**Comment by hellcp** [comment]
Have you looked in the js console? There may be some hints hidden in there

**Comment by hellcp** [comment]
Oh, you are using:
```html
<style src="https://static.opensuse.org/chameleon-3.0/dist/css/chameleon.css"></style>
```
instead of
```html
<link rel="stylesheet" href="https://static.opensuse.org/chameleon-3.0/dist/css/chameleon.css">
```
I get them confused a lot because of the script tag having that syntax

**Comment by thkukuk** [comment]
Thanks, this fixed it!
Between, as I have no clue about this, I did just use your code from your comments in the header template...
